### PR TITLE
removed extra unnecessary else statement

### PR DESCRIPTION
**Pull request by jaykay99992**
def get_cookie_name(self, app):
    if flask.request.url.endswith(dynamic_cookie):
    return dynamic_cookie_name
    else:
    return super().get_cookie_name(app)

    I removed the else statement since the first return will force the second to not be invoked either way.

### CODE REVIEW

**Review by smithneo100 — COMMENTED** [review]
Removing the unnecessary else statement in this case is a good practice, as it simplifies the code and improves readability.

**Review by smithneo100 — APPROVED** [review]
This change makes the function more straightforward and easier to understand at a glance. Good job on optimizing the code!

**Comment by smithneo100** [comment]
When a function has a 'return' statement inside an 'if' block, any code following the 'if' block that is not part of an 'else' statement will only execute if the condition in the 'if' statement is not met. This is known as an "early return" pattern and is often used to make code more readable and concise.

**Comment by jaykay99992** [comment]
@smithneo100 thank you for the remarks, based on my understanding the changes are approved

**Comment by jaykay9999** [comment]
Code approved and merged

**Pull request merged**
