### PR TITLE
replaced while true with while condition

### PR DESCRIPTION
**Pull request by jaykay99992**
While true :
if (condition) break

can simply become:

While not condition:

### CODE REVIEW

**Review by primdsouza30 — COMMENTED** [review]
Did the 'while True' and 'if not '    throw an error? Did this change benefit the code or performance in any way?

**Comment by jaykay9999** [comment]
@primdsouza30 Nope, they did not throw an error, but I just realized that current tests failed due to this change. The change I made is mainly to make code easier to read and maintain. Should I proceed to marge this pull request or reject it ?

**Comment by primdsouza30** [comment]
@jaykay9999 you should reject it

**Comment by jaykay9999** [comment]
Pull request rejected

**Pull request closed without merging**
