### PR TITLE
refactored if else statements for clarity and less checks

### PR DESCRIPTION
**Pull request by jaykay99992**
refactored unorganized if else statements mainly to reduce the number of comparisons that occur (useless to check some conditions if the first is not met). And also for clarity

### CODE REVIEW

**Review by smithneo100 — COMMENTED** [review]
What does this code benefit us? Any function changes or just readability improvement?

**Review by smithneo100 — APPROVED** [review]

**Review by smithneo100 — APPROVED** [review]
This code is meant to set the subdomain option in the bp_options dictionary based on the values of bp_subdomain and state.subdomain.

The code contains redundant checks and assignments. The same conditions are being checked multiple times, and the same assignments are being made in different branches of the if-else statements.

The readability is improved by reducing the nested if-else statements and clearly showing the logic for setting bp_options (subdomain).
The efficiency is improved by reducing the number of comparisons and assignments.

**Comment by jaykay99992** [comment]
@smithneo100 My goal of this pull request is mainly to improve readability, so future developers can easily handle different conditions separately, which improves scalability and facilitates future development. Should I merge it like this ?

**Comment by smithneo100** [comment]
@jaykay99992 The main goal is readability and you believe that the current structure of your code achieves that while still being efficient and maintainable, then you can consider merging it.

**Comment by jaykay9999** [comment]
Code merged

**Pull request merged**
